AirlinesWeb/Controllers/AirlinesController.cs
using Airlines.Bussines.Dto;
using Airlines.Bussines.Service;
using Airlines.Persistance.Basic.Entities;
using Airlines.Persistance.Basic.Repository;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace AirlinesWeb.Controllers
{
    public class AirlinesController : Controller
    {
        private readonly IAirlineService _airlineService;

        public AirlinesController(IAirlineService airlineService)
        {
            _airlineService = airlineService;
        }
        public IActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<AirlineDto> airlines = _airlineService.GetAirlines();
            return View(airlines.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public IActionResult AddNewAirline(AirlineDto airline, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (ModelState.IsValid)
            {
                TempData["Successful"] = "Airline has been added successfully!";
                _airlineService.AddAirline(airline);
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Unsuccessful"] = "Unvalid airline details!";
                List<AirlineDto> airlines = _airlineService.GetAirlines();
                return View("Index", airlines.ToPagedList(pageNumber, pageSize));
            }
        }


        [HttpPost]
        public IActionResult SearchAirline(SearchDto searchDto, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (ModelState.IsValid)
            {
                List<AirlineDto> airlines = _airlineService.GetAirlineFilter(searchDto.Filter, searchDto.SearchInput);
                return View("Index", airlines.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                
                List<AirlineDto> airlines = _airlineService.GetAirlines();
                return View("Index", airlines.ToPagedList(pageNumber, pageSize));
            }
        }
    }
}

AirlinesWeb/Controllers/FlightsController.cs
using Airlines.Bussines.Dto;
using Airlines.Bussines.Service;
using Airlines.Persistance.Basic.Entities;
using Airlines.Persistance.Basic.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using X.PagedList;

namespace AirlinesWeb.Controllers
{
    public class FlightsController : Controller
    {
        private readonly IFlightService _flightService;
        public FlightsController(IFlightService flightService)
        {
            _flightService = flightService;
        }

        public IActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<FlightDto> flights = _flightService.GetFlights();
            return View(flights.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public IActionResult AddNewFlight(FlightDto flight, int? page)
        {
            if(ModelState.IsValid)
            {
                TempData["Successful"] = "Flight has been added successfully!";
                _flightService.AddFlight(flight);
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Unsuccessful"] = "Unvalid flight details!";
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                List<FlightDto> flights = _flightService.GetFlights();
                return View("Index",flights.ToPagedList(pageNumber, pageSize));
            }
            
        }

        [HttpPost]
        public IActionResult SearchFlight(SearchDto searchDto, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (ModelState.IsValid)
            {
                List<FlightDto> flights = _flightService.GetFlightByFilter(searchDto.Filter, searchDto.SearchInput);
                return View("Index", flights.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                List<FlightDto> flights = _flightService.GetFlights();
                return View("Index", flights.ToPagedList(pageNumber, pageSize));
            }
        }
    }
}

AirlinesWeb/Controllers/HomeController.cs
using Airlines.Bussines.Dto;
using Airlines.Bussines.Service;
using Airlines.Persistance.Basic.Entities;
using Airlines.Persistance.Basic.Repository;
using AirlinesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AirlinesWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAirportService _airportService;
        private readonly IAirlineService _airlineService;
        private readonly IFlightService _flightService;

       
        public HomeController
            (ILogger<HomeController> logger, IAirportService airportService, IAirlineService airlineService, IFlightService flightService)
        {
            _logger = logger;
            _airportService = airportService;
            _airlineService = airlineService;
            _flightService = flightService;
        }

        public IActionResult Index()
        {
            int airpCount = _airportService.GetCount();
            int airlCount = _airlineService.GetCount();
            int flightCount = _flightService.GetCount();
            CountDto countDto = new CountDto(airpCount, airlCount, flightCount);
            return View(countDto);
        }

        


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AirlinesWeb/Views/Home/Index.cshtml
@using Airlines.Bussines.Dto
@section Styles {
    <link rel="stylesheet" href="~/css/index1.css" />
}

@model CountDto

<div class="content">
    <div class="h2">
        <p class="welcome">Welcome To Dashboard</p>
    </div>

    <div class="nav-links">
        <div class="entity-block">
            <div class="window">
                <p class="p1">
                    Airports
                </p>
                <img class="image" src="~/assets/mdi_airport.png" alt="Airports">
                <p class="p2">
                    @Model.AirportsCount
                </p>
            </div>
            <div class="add">
                <a class="add-button" asp-controller="Airports" asp-action="Index">
                    Add New Airport
                </a>
            </div>
        </div>
        <div class="entity-block">
            <div class="window">
                <p class="p1">
                    Airlines
                </p>
                <img class="image" src="~/assets/ri_plane-fill.png" alt="">
                <p class="p2">
                    @Model.AirlinesCount
                </p>
            </div>
            <div class="add">
                <a class="add-button" asp-controller="Airlines" asp-action="Index">
                    Add New Airline
                </a>
            </div>
        </div>

        <div class="entity-block">
            <div class="window">
                <p class="p1">
                    Flights
                </p>
                <img class="image" src="~/assets/carbon_flight-schedule.png" alt="">
                <p class="p2">
                    @Model.FlightsCount
                </p>
            </div>
            <div class="add">
                <a class="add-button" asp-controller="Flights" asp-action="Index">
                    Add New Flight
                </a>
            </div>
        </div>
    </div>
</div>