AirlinesWeb/Controllers/AirportsController.cs
using Airlines.Bussines.Dto;
using Airlines.Bussines.Service;
using Airlines.Persistance.Basic.Entities;
using Airlines.Persistance.Basic.EntitiesService;
using Airlines.Persistance.Basic.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using X.PagedList;

namespace AirlinesWeb.Controllers
{
    public class AirportsController : Controller
    {
        private readonly IAirportService _airportService;

        public AirportsController(IAirportService airportService)
        {
            _airportService = airportService;
        }
        public IActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<AirportDto> airports = _airportService.GetAirports();
            return View(airports.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public IActionResult AddNewAirport(AirportDto airportDto, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (ModelState.IsValid)
            {
                _airportService.AddAirport(airportDto);
                TempData["Successful"] = "Airport has been added successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Unsuccessful"] = "Unvalid airport details!";
                List<AirportDto> airports = _airportService.GetAirports();
                return View("Index", airports.ToPagedList(pageNumber, pageSize));
            }
        }

        [HttpPost]
        public IActionResult SearchAirport(SearchDto searchDto, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (ModelState.IsValid)
            {
                List<AirportDto> airports = _airportService.GetAirportFilter(searchDto.Filter, searchDto.SearchInput);
                return View("Index", airports.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                List<AirportDto> airports = _airportService.GetAirports();
                return View("Index", airports.ToPagedList(pageNumber, pageSize));
            }
        }
    }
}

AirlinesWeb/Views/Airports/Add.cshtml
@using Airlines.Bussines.Dto
@model AirportDto


<div class="form-container" id="form-container">
    <fieldset class="form-fieldset">
        <legend>
            Add New Airport
        </legend>
        <form class="form" id="form" asp-action="AddNewAirport" asp-controller="Airports" method="post" asp-validation-summary="Model">
            <label asp-for="@Model.Name"></label>
            <input asp-for="@Model.Name" id="name" name="name" />
            <span asp-validation-for="@Model.Name" id="valid-name" class="text-danger"></span>

            <label asp-for="@Model.Country"></label>
            <input asp-for="@Model.Country" id="country" name="country" />
            <span asp-validation-for="@Model.Country" id="valid-country" class="text-danger"></span>

            <label asp-for="@Model.City"></label>
            <input asp-for="@Model.City" id="city" name="city" />
            <span asp-validation-for="@Model.City" class="text-danger" id="valid-city"></span>

            <label asp-for="@Model.Code"></label>
            <input asp-for="@Model.Code" id="code" name="code" />
            <span asp-validation-for="@Model.Code" id="valid-code" class="text-danger"></span>

            <label asp-for="@Model.RunwaysCount"></label>
            <input asp-for="@Model.RunwaysCount" id="runwaysCount" name="runwaysCount" />
            <span asp-validation-for="@Model.RunwaysCount" id="valid-runways" class="text-danger"></span>

            <label asp-for="@Model.Founded"></label>
            <input asp-for="@Model.Founded" id="founded" name="founded" />
            <span asp-validation-for="@Model.Founded" id="valid-founded" class="text-danger"></span>

            <button class="submit" type="submit", id="submit">
                Submit
            </button>
        </form>
        @*   @section Scripts {
        @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
        } *@

    </fieldset>
</div>

AirlinesWeb/Views/Airports/AirportSearch.cshtml
@using Airlines.Bussines.Dto
@model SearchDto

<div class="search-container">

    <form class="search-form" asp-controller="Airports" asp-action="SearchAirport" method="post" asp-validation-summary="Model">
        <div class="search-menu">
            <input asp-for="@Model.SearchInput" id="searchInput" placeholder="Search...">
            <select class="search-field" id="searchField" asp-for="Filter">
                <option value="Name">Name</option>
                <option value="Country">Country</option>
                <option value="City">City</option>
            </select>
        </div>
        <button class="search-button">
            Search
        </button>
    </form>

</div>

AirlinesWeb/Views/Airports/Index.cshtml
@using Airlines.Bussines.Dto
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Airlines.Persistance.Basic.Entities
@using PagedList.Mvc

@{
    ViewData["Title"] = "Airports";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/js/showTable.js"></script>
    <script src="~/js/showForm.js"></script>
    <script src="~/js/animation.js"></script>
    <script src="~/js/airports/validation.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.3/dist/confetti.browser.min.js"></script>
}


@model X.PagedList.IPagedList<Airlines.Bussines.Dto.AirportDto>
@{
    AirportDto airportDto = new AirportDto();
}
<div class="content">
    @await Html.PartialAsync("AddedSuccessfully")
    <div class="h2">

        <a asp-controller="Home" asp-action="Index">
            <img class=sidebar src="~/assets/left sidebar.png" alt="">
        </a>
        <p class="text">Airports</p>
    </div>
    @{
        SearchDto searchDto = new SearchDto();
    }
    <div class="table-topline" id="table-topline">
        @await Html.PartialAsync("AirportSearch", searchDto)
        <div id="table" class="table-container">
            <table class="table">
                <tr class="titles">
                    <th>Name</th>
                    <th>Code</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Runways Count</th>
                    <th>Founded</th>
                </tr>
                @foreach (AirportDto airport in Model)
                {
                    <tr>
                        <td>@airport.Name</td>
                        <td>@airport.Code</td>
                        <td>@airport.City</td>
                        <td>@airport.Country</td>
                        <td>@airport.RunwaysCount</td>
                        <td>@airport.Founded</td>
                    </tr>
                }

            </table>
        </div>
        <div class="pagination-container">

            @for (int i = 1; i <= Model.PageCount; i++)
            {
                <a href="@Url.Action("Index", "Airports", new { page = i })" @(Model.PageNumber == i)>@i</a>

            }
            <button id="toggle" class="toggle">
            </button>
        </div>
    </div>
    <div class="show">
        <button class="show-button" id="show-button">
            Show Form
        </button>
    </div>
    @await Html.PartialAsync("Add", airportDto)
</div>